/**
 * pre-commit hook - Prevent committing sensitive data
 * Part of Automated Backup System (Matthew Berman Style)
 * 
 * Install: Copy to .git/hooks/pre-commit and make executable
 * Or: ln -s ../../backup-system/scripts/pre-commit .git/hooks/pre-commit
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const WORKSPACE_DIR = process.env.WORKSPACE_DIR || '/Users/andrewbot/.openclaw/workspace';

// Patterns that indicate secrets
const SECRET_PATTERNS = [
  // AWS
  /AKIA[0-9A-Z]{16}/g,
  // Generic API keys (hex strings 32+ chars)
  /[0-9a-f]{32,}/gi,
  // Private keys
  /-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/g,
  // Tokens
  /eyJ[A-Za-z0-9-_]+\.eyJ[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+/g,
  // GitHub tokens
  /gh[pousr]_[A-Za-z0-9_]{36,}/g,
  // Generic bearer tokens
  /Bearer [A-Za-z0-9\-._~+/]+=*/gi,
  // Passwords in configs
  /password\s*[=:]\s*["'][^"']{8,}["']/gi,
  /passwd\s*[=:]\s*["'][^"']{8,}["']/gi,
  // Secret keys
  /secret[_-]?key\s*[=:]\s*["'][^"']{8,}["']/gi,
  /api[_-]?key\s*[=:]\s*["'][A-Za-z0-9\-_]{20,}["']/gi,
  // Database connection strings
  /mongodb(\+srv)?:\/\/[^:]+:[^@]+@/gi,
  /postgres(ql)?:\/\/[^:]+:[^@]+@/gi,
  /mysql:\/\/[^:]+:[^@]+@/gi,
  /redis:\/\/[^:]+:[^@]+@/gi,
];

// Files to always skip
const SKIP_PATTERNS = [
  /\.(jpg|jpeg|png|gif|ico|svg)$/i,
  /\.git\//,
  /node_modules\//,
  /\.env$/,
  /\.env\.local$/,
  /secrets\//,
];

interface ScanResult {
  file: string;
  line?: number;
  match: string;
  pattern: string;
}

function shouldSkip(filePath: string): boolean {
  return SKIP_PATTERNS.some(pattern => pattern.test(filePath));
}

function scanFile(filePath: string): ScanResult[] {
  const results: ScanResult[] = [];
  
  if (shouldSkip(filePath)) {
    return results;
  }
  
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split('\n');
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      
      for (const pattern of SECRET_PATTERNS) {
        pattern.lastIndex = 0;
        if (pattern.test(line)) {
          results.push({
            file: filePath,
            line: i + 1,
            match: line.substring(0, 80) + (line.length > 80 ? '...' : ''),
            pattern: pattern.source
          });
        }
      }
    }
  } catch (error) {
    // Binary file or unreadable
  }
  
  return results;
}

function getStagedFiles(): string[] {
  try {
    const output = execSync('git diff --cached --name-only', {
      encoding: 'utf8',
      cwd: WORKSPACE_DIR
    });
    return output.split('\n').filter(Boolean);
  } catch {
    return [];
  }
}

export function runPreCommitCheck(): boolean {
  console.log('🔒 Running secret detection scan...\n');
  
  const files = getStagedFiles();
  
  if (files.length === 0) {
    console.log('ℹ️  No staged files to scan');
    return true;
  }
  
  console.log(`   Scanning ${files.length} file(s)...\n`);
  
  let hasSecrets = false;
  
  for (const file of files) {
    const fullPath = path.join(WORKSPACE_DIR, file);
    const results = scanFile(fullPath);
    
    if (results.length > 0) {
      hasSecrets = true;
      console.log(`🚨 SEcrets detected in: ${file}`);
      
      for (const result of results) {
        console.log(`   Line ${result.line}: ${result.match}`);
      }
      console.log('');
    }
  }
  
  if (hasSecrets) {
    console.log('❌ COMMIT BLOCKED: Potential secrets detected');
    console.log('\nIf you are sure this is safe, force commit with:');
    console.log('   git commit --no-verify -m "your message"');
    console.log('\nOr fix the issues and try again.');
    return false;
  }
  
  console.log('✅ No secrets detected - commit allowed');
  return true;
}

// Install pre-commit hook
export function installHook(): void {
  const gitDir = path.join(WORKSPACE_DIR, '.git');
  const hooksDir = path.join(gitDir, 'hooks');
  const hookPath = path.join(hooksDir, 'pre-commit');
  
  // Ensure hooks directory exists
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }
  
  // Create hook content
  const hookContent = `#!/bin/bash
# Pre-commit hook - Secret detection
# Auto-generated by backup-system

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NODE_BIN="${SCRIPT_DIR}/../../backup-system/node_modules/.bin/node"

if [ -f "${SCRIPT_DIR}/../../backup-system/src/pre-commit.js" ]; then
  cd "${SCRIPT_DIR}/../.."
  node -e "
    const fs = require('fs');
    const path = require('path');
    
    const patterns = [
      /AKIA[0-9A-Z]{16}/g,
      /[0-9a-f]{32,}/gi,
      /-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/g,
      /eyJ[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+/g,
      /gh[pousr]_[A-Za-z0-9_]{36,}/g,
      /Bearer [A-Za-z0-9\\-._~+/]+=*/gi,
    ];
    
    const skip = /\\.(jpg|jpeg|png|gif|ico|svg)$/i;
    
    const files = require('child_process').execSync('git diff --cached --name-only', {encoding:'utf8'}).split('\\n').filter(Boolean);
    let found = false;
    
    for (const file of files) {
      if (skip.test(file)) continue;
      try {
        const content = fs.readFileSync(file, 'utf8');
        for (const p of patterns) {
          p.lastIndex = 0;
          if (p.test(content)) {
            console.log('🚨 SECRET DETECTED in ' + file);
            found = true;
          }
        }
      } catch {}
    }
    
    if (found) {
      console.log('❌ COMMIT BLOCKED - secrets detected');
      console.log('Force with: git commit --no-verify');
      process.exit(1);
    }
  "
fi
`;
  
  fs.writeFileSync(hookPath, hookContent);
  fs.chmodSync(hookPath, 0o755);
  
  console.log('✅ Pre-commit hook installed');
}

// CLI mode
if (require.main === module) {
  const args = process.argv.slice(2);
  
  if (args[0] === 'install') {
    installHook();
  } else {
    const passed = runPreCommitCheck();
    process.exit(passed ? 0 : 1);
  }
}
